redis:
  host: 127.0.0.1
  port: 6379
  password: 123456
  pool:
    max-total: 10
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: 3000
    # 连接池中的最大空闲连接
    max-idle: 5
    # 连接池中的最小空闲连接
    min-idle: 2
  # 超时时间（毫秒）
  timeout: 10000