server:
    port: 8080
spring:
    application:
        name: spring-boot-redis-demo
    redis:
        host: 127.0.0.1
        port: 6379
        # redis数据库索引
        database: 10
        password: 123456
        lettuce:
            pool:
                max-active: 10
                # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: 3000
                # 连接池中的最大空闲连接
                max-idle: 5
                # 连接池中的最小空闲连接
                min-idle: 2
        # 超时时间（毫秒）
        timeout: 10000